### ISSUE TITLE
always return error for android

### ISSUE THREAD

**Issue by ubia** [TIGERB/easy-mipush#1]
{"ios":{"result":"ok","trace_id":"Xlx01b55481730584523K9","code":0,"data":{"id":"ulx01b55481730584912ba"},"description":"成功","info":"Received push messages for 1 USER_ACCOUNT"},"android":{"result":"error","reason":"Title or Description is empty!","trace_id":"Xcm09b39481730584495Ud","code":65011,"description":"未提供参数"}}

**Comment by TIGERB** [comment]
Argument  description is empty?

Can you give me your example by used it?

I'will fix it!

**Comment by TIGERB** [comment]
fixed~

thx~
